[package]
name = "mlzlog"
version = "0.3.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
license = "MIT/Apache-2.0"
description = "A collection of log4rs tools to log like the mlzlog Python package"
repository = "https://github.com/birkenfeld/mlzlog-rs"
documentation = "http://docs.rs/mlzlog"
keywords = ["logging", "mlz", "colored", "rolling"]

[dependencies.log4rs]
version = "0.8"
default-features = false
features = ["pattern_encoder", "simple_writer"]

[dependencies]
log = "0.4"
log-mdc = "0.1"
time = "0.1.38"
ansi_term = "0.10"
parking_lot = "0.5"
